# coding: utf-8

"""
    ADP APIs

    ADP API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import os
from pprint import pprint
from adp_workforce_now_python_sdk import AdpWorkforceNow

class TestSimple(unittest.TestCase):
    def setUp(self):
        pass

    def test_client(self):
        adpworkforcenow = AdpWorkforceNow(
        )
        self.assertIsNotNone(adpworkforcenow)

    def tearDown(self):
        pass


if __name__ == "__main__":
    unittest.main()
