# coding: utf-8
"""
    ADP APIs

    ADP API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import typing
import inspect
from datetime import date, datetime
from adp_workforce_now_python_sdk.client_custom import ClientCustom
from adp_workforce_now_python_sdk.configuration import Configuration
from adp_workforce_now_python_sdk.api_client import ApiClient
from adp_workforce_now_python_sdk.type_util import copy_signature
from adp_workforce_now_python_sdk.apis.tags.hr_api import HRApi
from adp_workforce_now_python_sdk.apis.tags.payroll_api import PayrollApi
from adp_workforce_now_python_sdk.apis.tags.token_request_api import TokenRequestApi



class AdpWorkforceNow(ClientCustom):

    def __init__(self, configuration: typing.Union[Configuration, None] = None, **kwargs):
        super().__init__(configuration, **kwargs)
        if (len(kwargs) > 0):
            configuration = Configuration(**kwargs)
        if (configuration is None):
            raise Exception("configuration is required")
        api_client = ApiClient(configuration)
        self.hr: HRApi = HRApi(api_client)
        self.payroll: PayrollApi = PayrollApi(api_client)
        self.token_request: TokenRequestApi = TokenRequestApi(api_client)
