# coding: utf-8

"""
    ADP APIs

    ADP API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from adp_workforce_now_python_sdk.paths.core_v1_operations_worker_information_management_hr_v2_workers_key.get import CheckAsyncRequestStatusRaw
from adp_workforce_now_python_sdk.paths.hr_v2_workers_anthony_albright_aoid.get import GetWorkerByAoidRaw
from adp_workforce_now_python_sdk.paths.hr_v2_worker_demographics_anthony_albright_aoid.get import GetWorkerDemographicsByAoidRaw
from adp_workforce_now_python_sdk.paths.hr_v2_workers.get import ListTop5PreventCacheRaw
from adp_workforce_now_python_sdk.paths.hr_v2_worker_demographics.get import ListTop5PreventCache0Raw


class HRApiRaw(
    CheckAsyncRequestStatusRaw,
    GetWorkerByAoidRaw,
    GetWorkerDemographicsByAoidRaw,
    ListTop5PreventCacheRaw,
    ListTop5PreventCache0Raw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
