# coding: utf-8

"""
    ADP APIs

    ADP API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from adp_workforce_now_python_sdk.paths.core_v1_operations_worker_information_management_hr_v2_workers_key.get import CheckAsyncRequestStatus
from adp_workforce_now_python_sdk.paths.hr_v2_workers_anthony_albright_aoid.get import GetWorkerByAoid
from adp_workforce_now_python_sdk.paths.hr_v2_worker_demographics_anthony_albright_aoid.get import GetWorkerDemographicsByAoid
from adp_workforce_now_python_sdk.paths.hr_v2_workers.get import ListTop5PreventCache
from adp_workforce_now_python_sdk.paths.hr_v2_worker_demographics.get import ListTop5PreventCache0
from adp_workforce_now_python_sdk.apis.tags.hr_api_raw import HRApiRaw


class HRApi(
    CheckAsyncRequestStatus,
    GetWorkerByAoid,
    GetWorkerDemographicsByAoid,
    ListTop5PreventCache,
    ListTop5PreventCache0,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: HRApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = HRApiRaw(api_client)
