# coding: utf-8

"""
    ADP APIs

    ADP API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from adp_workforce_now_python_sdk.paths.payroll_v1_payroll_output.get import ListPayrollOutputs
from adp_workforce_now_python_sdk.apis.tags.payroll_api_raw import PayrollApiRaw


class PayrollApi(
    ListPayrollOutputs,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: PayrollApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = PayrollApiRaw(api_client)
