# coding: utf-8

"""
    ADP APIs

    ADP API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from adp_workforce_now_python_sdk.paths.auth_oauth_v2_token.post import CreateWithAuthorizationHeaderRaw


class TokenRequestApiRaw(
    CreateWithAuthorizationHeaderRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
