# coding: utf-8

"""
    ADP APIs

    ADP API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from adp_workforce_now_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from adp_workforce_now_python_sdk.api_response import AsyncGeneratorResponse
from adp_workforce_now_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from adp_workforce_now_python_sdk import schemas  # noqa: F401



from ...api_client import Dictionary

from . import path

# Query params
FilterSchema = schemas.StrSchema
CountSchema = schemas.StrSchema
UseCacheSchema = schemas.StrSchema
LevelSchema = schemas.StrSchema
SelectSchema = schemas.StrSchema
RequestRequiredQueryParams = typing_extensions.TypedDict(
    'RequestRequiredQueryParams',
    {
    }
)
RequestOptionalQueryParams = typing_extensions.TypedDict(
    'RequestOptionalQueryParams',
    {
        '$filter': typing.Union[FilterSchema, str, ],
        '$count': typing.Union[CountSchema, str, ],
        'use-cache': typing.Union[UseCacheSchema, str, ],
        'level': typing.Union[LevelSchema, str, ],
        '$select': typing.Union[SelectSchema, str, ],
    },
    total=False
)


class RequestQueryParams(RequestRequiredQueryParams, RequestOptionalQueryParams):
    pass


request_query_filter = api_client.QueryParameter(
    name="$filter",
    style=api_client.ParameterStyle.FORM,
    schema=FilterSchema,
    explode=True,
)
request_query_count = api_client.QueryParameter(
    name="$count",
    style=api_client.ParameterStyle.FORM,
    schema=CountSchema,
    explode=True,
)
request_query_use_cache = api_client.QueryParameter(
    name="use-cache",
    style=api_client.ParameterStyle.FORM,
    schema=UseCacheSchema,
    explode=True,
)
request_query_level = api_client.QueryParameter(
    name="level",
    style=api_client.ParameterStyle.FORM,
    schema=LevelSchema,
    explode=True,
)
request_query_select = api_client.QueryParameter(
    name="$select",
    style=api_client.ParameterStyle.FORM,
    schema=SelectSchema,
    explode=True,
)
# body param
SchemaForRequestBodyApplicationOctetStream = schemas.AnyTypeSchema


request_body_body = api_client.RequestBody(
    content={
        'application/octet-stream': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationOctetStream),
    },
)


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: schemas.Unset = schemas.unset


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: schemas.Unset = schemas.unset


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
)
_status_code_to_response = {
    '200': _response_for_200,
}


class BaseApi(api_client.Api):

    def _list_payroll_outputs_mapped_args(
        self,
        filter: typing.Optional[str] = None,
        count: typing.Optional[str] = None,
        use_cache: typing.Optional[str] = None,
        level: typing.Optional[str] = None,
        select: typing.Optional[str] = None,
        body: typing.Optional[typing.Union[bool, date, datetime, dict, float, int, list, str, None]] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _query_params = {}
        _body = {}
        args.body = body if body is not None else _body
        if filter is not None:
            _query_params["$filter"] = filter
        if count is not None:
            _query_params["$count"] = count
        if use_cache is not None:
            _query_params["use-cache"] = use_cache
        if level is not None:
            _query_params["level"] = level
        if select is not None:
            _query_params["$select"] = select
        args.query = _query_params
        return args

    async def _alist_payroll_outputs_oapg(
        self,
        body: typing.Any = None,
            query_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        content_type: str = 'application/octet-stream',
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Payroll Outputs V1 (List for Region / Company Code / Year / Week)
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        used_path = path.value
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_filter,
            request_query_count,
            request_query_use_cache,
            request_query_level,
            request_query_select,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        method = 'get'.upper()
        _headers.add('Content-Type', content_type)
    
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/payroll/v1/payroll-output',
            body=body,
            headers=_headers,
        )
        if body is not schemas.unset:
            serialized_data = request_body_body.serialize(body, content_type)
            if 'fields' in serialized_data:
                _fields = serialized_data['fields']
            elif 'body' in serialized_data:
                _body = serialized_data['body']
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _list_payroll_outputs_oapg(
        self,
        body: typing.Any = None,
            query_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        content_type: str = 'application/octet-stream',
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Payroll Outputs V1 (List for Region / Company Code / Year / Week)
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        used_path = path.value
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_filter,
            request_query_count,
            request_query_use_cache,
            request_query_level,
            request_query_select,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        method = 'get'.upper()
        _headers.add('Content-Type', content_type)
    
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/payroll/v1/payroll-output',
            body=body,
            headers=_headers,
        )
        if body is not schemas.unset:
            serialized_data = request_body_body.serialize(body, content_type)
            if 'fields' in serialized_data:
                _fields = serialized_data['fields']
            elif 'body' in serialized_data:
                _body = serialized_data['body']
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class ListPayrollOutputsRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def alist_payroll_outputs(
        self,
        filter: typing.Optional[str] = None,
        count: typing.Optional[str] = None,
        use_cache: typing.Optional[str] = None,
        level: typing.Optional[str] = None,
        select: typing.Optional[str] = None,
        body: typing.Optional[typing.Union[bool, date, datetime, dict, float, int, list, str, None]] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._list_payroll_outputs_mapped_args(
            body=body,
            filter=filter,
            count=count,
            use_cache=use_cache,
            level=level,
            select=select,
        )
        return await self._alist_payroll_outputs_oapg(
            body=args.body,
            query_params=args.query,
            **kwargs,
        )
    
    def list_payroll_outputs(
        self,
        filter: typing.Optional[str] = None,
        count: typing.Optional[str] = None,
        use_cache: typing.Optional[str] = None,
        level: typing.Optional[str] = None,
        select: typing.Optional[str] = None,
        body: typing.Optional[typing.Union[bool, date, datetime, dict, float, int, list, str, None]] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._list_payroll_outputs_mapped_args(
            body=body,
            filter=filter,
            count=count,
            use_cache=use_cache,
            level=level,
            select=select,
        )
        return self._list_payroll_outputs_oapg(
            body=args.body,
            query_params=args.query,
        )

class ListPayrollOutputs(BaseApi):

    async def alist_payroll_outputs(
        self,
        filter: typing.Optional[str] = None,
        count: typing.Optional[str] = None,
        use_cache: typing.Optional[str] = None,
        level: typing.Optional[str] = None,
        select: typing.Optional[str] = None,
        body: typing.Optional[typing.Union[bool, date, datetime, dict, float, int, list, str, None]] = None,
        validate: bool = False,
        **kwargs,
    ) -> None:
        raw_response = await self.raw.alist_payroll_outputs(
            body=body,
            filter=filter,
            count=count,
            use_cache=use_cache,
            level=level,
            select=select,
            **kwargs,
        )
    
    
    def list_payroll_outputs(
        self,
        filter: typing.Optional[str] = None,
        count: typing.Optional[str] = None,
        use_cache: typing.Optional[str] = None,
        level: typing.Optional[str] = None,
        select: typing.Optional[str] = None,
        body: typing.Optional[typing.Union[bool, date, datetime, dict, float, int, list, str, None]] = None,
        validate: bool = False,
    ) -> None:
        raw_response = self.raw.list_payroll_outputs(
            body=body,
            filter=filter,
            count=count,
            use_cache=use_cache,
            level=level,
            select=select,
        )


class ApiForget(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def aget(
        self,
        filter: typing.Optional[str] = None,
        count: typing.Optional[str] = None,
        use_cache: typing.Optional[str] = None,
        level: typing.Optional[str] = None,
        select: typing.Optional[str] = None,
        body: typing.Optional[typing.Union[bool, date, datetime, dict, float, int, list, str, None]] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._list_payroll_outputs_mapped_args(
            body=body,
            filter=filter,
            count=count,
            use_cache=use_cache,
            level=level,
            select=select,
        )
        return await self._alist_payroll_outputs_oapg(
            body=args.body,
            query_params=args.query,
            **kwargs,
        )
    
    def get(
        self,
        filter: typing.Optional[str] = None,
        count: typing.Optional[str] = None,
        use_cache: typing.Optional[str] = None,
        level: typing.Optional[str] = None,
        select: typing.Optional[str] = None,
        body: typing.Optional[typing.Union[bool, date, datetime, dict, float, int, list, str, None]] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._list_payroll_outputs_mapped_args(
            body=body,
            filter=filter,
            count=count,
            use_cache=use_cache,
            level=level,
            select=select,
        )
        return self._list_payroll_outputs_oapg(
            body=args.body,
            query_params=args.query,
        )

