# coding: utf-8

"""
    ADP APIs

    ADP API endpoints.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import adp_workforce_now_python_sdk
from adp_workforce_now_python_sdk.paths.hr_v2_workers_anthony_albright_aoid import get
from adp_workforce_now_python_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestHrV2WorkersAnthonyAlbrightAoid(ApiTestMixin, unittest.TestCase):
    """
    HrV2WorkersAnthonyAlbrightAoid unit test stubs
        Worker V2 (Single by AOID)
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 200
    response_body = ''


if __name__ == '__main__':
    unittest.main()
